# Generated by Django 5.1.3 on 2024-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do cartão', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição do cartão')),
                ('image', models.ImageField(blank=True, help_text='Imagem opcional', null=True, upload_to='card_images/')),
                ('url', models.URLField(blank=True, help_text="URL para cartões do tipo 'Link'")),
                ('card_type', models.CharField(choices=[('LINK', 'Link Card'), ('INFO', 'Informational Card'), ('FUNCTION', 'Functional Card')], default='LINK', help_text='Tipo de cartão', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
