# Generated by Django 5.1.3 on 2024-11-19 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_card_open_in_new_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='open_in_new_tab',
        ),
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.RemoveField(
            model_name='card',
            name='url',
        ),
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='card',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='update_frequency',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('public_ip', 'IP Público'), ('uptime_kuma', 'Uptime Kuma'), ('docker', 'Docker Info'), ('server', 'Informações do Servidor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(),
        ),
    ]
