# Generated by Django 5.1.3 on 2024-11-19 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_card_active_remove_card_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
