# Generated by Django 5.1.3 on 2024-11-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('card_type', models.CharField(choices=[('docker', 'Docker'), ('public_ip', 'Public IP')], max_length=100)),
                ('frequency', models.IntegerField(default=30)),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='PublicIPCard',
        ),
    ]
