# Generated by Django 5.1.3 on 2024-11-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_publicipcard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicIPCard',
        ),
    ]
